In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("My first NumPy array:", arr)
print("Mean:", np.mean(arr))

My first NumPy array: [1 2 3 4 5]
Mean: 3.0


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("1D array:", arr)
print("Type:", type(arr))
print("Shape:", arr.shape)  # (5,) = 5 elements

1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)


In [1]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D array (matrix):")
print(matrix)
print("Shape:", matrix.shape) 


2D array (matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [5]:
import numpy as np
zeros = np.zeros((3, 3))
print("\nZeros:")
print(zeros)
ones = np.ones((2, 4))
print("\nOnes:")
print(ones)


Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
import numpy as np
range_arr = np.arange(0, 10, 2)  # start, stop, step
print( range_arr)

[0 2 4 6 8]


In [8]:
import numpy as np
random_arr = np.random.rand(3, 3)  # Random between 0-1
print("\nRandom array:")
print(random_arr)



Random array:
[[0.66162598 0.34653284 0.90999436]
 [0.23186346 0.70226484 0.89310245]
 [0.61649583 0.36980185 0.92777756]]


In [15]:
import numpy as np
#random_arr = np.random.rand(3, 3)  # Random between 0-1
#print("\nRandom array:")
# agar random number hame usa 1 ya 100 ka bich ka range mai chaiye 
random_arr= np.random.randint(1, 100, size=(2,2))#yaha pa jo (2,2) hai wo 2 array ka form mai output de raha hai
print(random_arr)


[[ 6 83]
 [21 57]]


In [31]:
# INDEXING & SLICING 
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Get one element (0-indexed)
print("\nElement at index 0:", arr[0])
print("Element at index 2:", arr[2])

# Slice (start:stop, stop is exclusive)
print("Elements 1-3:", arr[1:4])
print("Last 2 elements:", arr[-2:])

# 2D indexing ye thoda imp hota hai ye bata ta hai ki 2d array mai kaisa ek row ya colum ko print karwana hai
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix element at [2, 2]:", matrix[1, 2])  # Row 0, Col 2
print("First row:", matrix[1,:])
print("First column:", matrix[:, 2])


Element at index 0: 10
Element at index 2: 30
Elements 1-3: [20 30 40]
Last 2 elements: [40 50]

Matrix element at [2, 2]: 6
First row: [4 5 6]
First column: [3 6 9]


In [33]:
import numpy as np # most important concept 
arr = np.array([1, 2, 3, 4, 5])

print("\narr + 10:", arr + 10)
print("arr * 2:", arr * 2)
print("arr ** 2 (square):", arr ** 2)

# Math functions
print("Square root:", np.sqrt(arr))
print("Log:", np.log(arr))

# Statistics
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std dev:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))



arr + 10: [11 12 13 14 15]
arr * 2: [ 2  4  6  8 10]
arr ** 2 (square): [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Mean: 3.0
Median: 3.0
Std dev: 1.4142135623730951
Min: 1
Max: 5


In [34]:
import numpy as np
arr = np.arange(12)
print("\nOriginal:", arr, "Shape:", arr.shape)

reshaped = arr.reshape(3, 4)
print("Reshaped to (3, 4):")
print(reshaped)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] Shape: (12,)
Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
